package com.example.lab08;

import java.util.ArrayList;
import java.util.List;

public class CustomList {
    private List<City> cities;

    public CustomList() {
        this.cities = new ArrayList<>();
    }

    public void addCity(City city) {
        cities.add(city);
    }


    /**
     * This function was generated by Gemini 3, Google Deepmind
     * I'm not getting a red test case on the CI on Github
     * I gave it the demo instructions explained my problem
     * 04/03/26
     */
    public boolean hasCity(City city) {
        // This makes the code compile, but the test will fail
        return false;
    }

    // Will be implemented later using TDD (leave blank for now)
    // public boolean hasCity(City city) { ... }
}
